export const CANTEEN_FILTER_ACTIONS = {
    SET_BED: 'SET_BED',
    SET_PATIENT: 'SET_PATIENT',
    SET_MEAL_ID: 'SET_MEAL_ID',
    SET_TYPE: 'SET_TYPE',
    SET_SEARCH: 'SET_SEARCH',
    SET_STATUS: 'SET_STATUS',
    RESET_ALL: 'RESET_ALL'
}