export const FILTER_ACTIONS = {
    SET_NURSING_STATION: 'SET_NURSING_STATION',
    SET_NURSING_BED: 'SET_NURSING_BED',
    SET_DIET_NAME: 'SET_DIET_NAME',
    SET_DIET_PATIENT: 'SET_DIET_PATIENT',
    RESET_ALL: 'RESET_ALL',
    SET_PT_SEARCH: 'SET_PT_SEARCH',
    SET_DIET_TYPE: 'SET_DIET_TYPE',
    SET_ASSIGNEE: 'SET_ASSIGNEE',
    SET_SELECTED_PATIENTS: 'SET_SELECTED_PATIENTS',
    TOGGLE_SELECTED_PATIENT: 'TOGGLE_SELECTED_PATIENT',
    CLEAR_SELECTED_PATIENTS: 'CLEAR_SELECTED_PATIENTS',
    REMOVE_SELECTED_PATIENT: 'REMOVE_SELECTED_PATIENT',

}
