export const ActionTyps = {
    APP_SIDEBAR_SHOW: "set",
    FETCH_LOGIN: "FETCH_LOGIN",
    FETCH_MODULE_NAME_LIST: "FETCH_MODULE_NAME_LIST",
    FETCH_USER_GROUP_NAME: "FETCH_USER_GROUP_NAME",
    FETCH_MENU_NAME: "FETCH_MENU_NAME",
    FETCH_DEPARTMENT: "FETCH_DEPARTMENT"
}
