export const ActionTyps = {
    APP_SIDEBAR_SHOW: "set",
    FETCH_LOGIN: "FETCH_LOGIN",
    FETCH_MODULE_NAME_LIST: "FETCH_MODULE_NAME_LIST",
    FETCH_USER_GROUP_NAME: "FETCH_USER_GROUP_NAME",
    FETCH_MENU_NAME: "FETCH_MENU_NAME",
    FETCH_DEPARTMENT: "FETCH_DEPARTMENT",
    FETCH_COMPLAINT_DEPARTMENT: "FETCH_COMPLAINT_DEPARTMENT",
    FETCH_HIC_POLICY: "FETCH_HIC_POLICY",
    FETCH_REQUEST_TYPE: "FETCH_REQUEST_TYPE",
    FETCH_DEPARTMENT_SECTION: "FETCH_DEPARTMENT_SECTION",
    FETCH_COMPLAINT_TYPE: "  FETCH_COMPLAINT_TYPE",
    FETCH_EMP_NAME_LIST: "FETCH_EMP_NAME_LIST",
    FETCH_MODULEGROUP_LIST: "FETCH_MODULEGROUP_LIST",
    FETCH_ASSET_TYPE: " FETCH_ASSET_TYPE",
    FETCH_SUBMODULE_GROUP: "FETCH_SUBMODULE_GROUPs",
    FETCH_BRANCH: "FETCH_BRANCH",
    FETCH_DESIGNATION: "FETCH_DESIGNATION"
}
